# Generated by Django 3.2.9 on 2022-01-10 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_addprojectdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='addprojectdata',
            name='prid',
            field=models.IntegerField(default=1, max_length=35),
            preserve_default=False,
        ),
    ]
