# Generated by Django 3.2.9 on 2022-01-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_addprojectdata_prid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addprojectdata',
            name='prid',
            field=models.CharField(max_length=35),
        ),
    ]
