# Generated by Django 3.2.9 on 2022-01-12 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0005_addtaskdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addtaskdata',
            old_name='Project_ID',
            new_name='prid',
        ),
        migrations.AlterField(
            model_name='addprojectdata',
            name='prduration',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='addprojectdata',
            name='prid',
            field=models.CharField(max_length=35, unique=True),
        ),
        migrations.AlterField(
            model_name='addtaskdata',
            name='Current_Time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='addtaskdata',
            name='Task_ID',
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
