# Generated by Django 3.2.9 on 2022-01-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0006_auto_20220111_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addprojectdata',
            name='prid',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='addtaskdata',
            name='Task_ID',
            field=models.CharField(max_length=35),
        ),
    ]
