# Generated by Django 3.2.9 on 2022-01-12 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0007_auto_20220111_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addprojectdata',
            name='prduration',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='addtaskdata',
            name='Current_Time',
            field=models.CharField(max_length=35),
        ),
    ]
