# Generated by Django 3.2.9 on 2022-01-12 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0008_auto_20220111_2008'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddTaskData',
        ),
    ]
