# Generated by Django 3.2.9 on 2022-01-13 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0013_alter_addtaskdata_current_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddData',
        ),
        migrations.DeleteModel(
            name='AddProjectdata',
        ),
        migrations.DeleteModel(
            name='AddTaskData',
        ),
    ]
