# Generated by Django 3.2.9 on 2022-01-16 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0015_adddata_addprojectdata_addtaskdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddData',
        ),
        migrations.DeleteModel(
            name='AddProjectdata',
        ),
        migrations.DeleteModel(
            name='AddTaskData',
        ),
    ]
