# Generated by Django 3.2.9 on 2022-01-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0017_addtaskdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtaskdata',
            name='Current_Time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
