# Generated by Django 3.2.9 on 2022-01-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0022_alter_addtaskdata_current_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProjectdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prid', models.CharField(max_length=35)),
                ('prname', models.CharField(max_length=25)),
                ('prduration', models.CharField(max_length=25)),
                ('prstartdate', models.DateField()),
                ('prhandalar', models.CharField(max_length=35)),
                ('prdatails', models.CharField(max_length=35)),
                ('prstatus', models.CharField(max_length=35)),
            ],
        ),
    ]
