# Generated by Django 3.2.9 on 2022-01-18 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0024_auto_20220117_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtaskdata',
            name='Current_Time',
            field=models.TimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
