# Generated by Django 3.2.9 on 2022-01-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0026_alter_addtaskdata_current_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtaskdata',
            name='User',
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addtaskdata',
            name='Current_Time',
            field=models.TimeField(),
        ),
    ]
