# Generated by Django 3.2.9 on 2022-01-19 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0027_auto_20220119_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtaskdata',
            name='User',
        ),
    ]
