# Generated by Django 3.2.9 on 2022-01-19 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0028_remove_addtaskdata_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddEmpData',
        ),
        migrations.DeleteModel(
            name='AddProjectdata',
        ),
        migrations.DeleteModel(
            name='AddTaskData',
        ),
    ]
