# Generated by Django 3.2.9 on 2022-01-20 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0030_addempdata_addprojectdata_addtaskdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddEmpData',
        ),
        migrations.DeleteModel(
            name='AddProjectdata',
        ),
        migrations.DeleteModel(
            name='AddTaskData',
        ),
    ]
