# Generated by Django 3.2.9 on 2022-01-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0031_auto_20220119_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddEmpData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=35)),
                ('email', models.CharField(max_length=35)),
                ('password', models.CharField(max_length=35)),
                ('designation', models.CharField(max_length=35)),
                ('department', models.CharField(max_length=35)),
                ('Gender', models.CharField(max_length=35)),
                ('mobile', models.CharField(max_length=35)),
                ('dob', models.DateField()),
                ('Address', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='AddProjectdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prid', models.CharField(max_length=35)),
                ('prname', models.CharField(max_length=25)),
                ('prduration', models.CharField(max_length=25)),
                ('prstartdate', models.DateField()),
                ('prhandalar', models.CharField(max_length=35)),
                ('prdatails', models.CharField(max_length=35)),
                ('prstatus', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='AddTaskData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_ID', models.CharField(max_length=20)),
                ('Project_ID', models.CharField(max_length=25)),
                ('Task_Name', models.CharField(max_length=35)),
                ('User', models.CharField(max_length=20)),
                ('Task_duration', models.CharField(max_length=35)),
                ('Current_Time', models.TimeField()),
                ('Task_Status', models.CharField(max_length=35)),
                ('Task_Details', models.CharField(max_length=35)),
            ],
        ),
    ]
