# Generated by Django 3.2.9 on 2022-01-22 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0034_addempdata_addprojectdata_addtaskdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddEmpData',
        ),
    ]
