# Generated by Django 3.2.9 on 2022-01-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0036_addempdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addempdata',
            name='dob',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='addprojectdata',
            name='prstartdate',
            field=models.DateField(auto_now=True),
        ),
    ]
