# Generated by Django 3.2.9 on 2022-01-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0037_auto_20220125_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trid', models.CharField(max_length=35)),
                ('USername', models.CharField(max_length=35)),
                ('SystemDate', models.DateField()),
                ('projctid', models.CharField(max_length=35)),
                ('taskid', models.CharField(max_length=35)),
                ('trdate', models.DateField()),
                ('ScreenShot', models.CharField(max_length=255)),
            ],
        ),
    ]
