# Generated by Django 3.2.9 on 2022-01-28 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0038_tracker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='trid',
        ),
    ]
