# Generated by Django 3.2.9 on 2022-01-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0039_remove_tracker_trid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='SystemDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='trdate',
            field=models.DateField(auto_now=True),
        ),
    ]
