# Generated by Django 3.2.9 on 2022-01-29 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0040_auto_20220128_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='ScreenShot',
        ),
    ]
