# Generated by Django 3.2.9 on 2022-01-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0042_rename_systemdate_tracker_sysdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='Sysdate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='trdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
