# Generated by Django 3.2.9 on 2022-01-29 02:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0043_auto_20220128_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='Sysdate',
            field=models.DateField(default=datetime.datetime(2022, 1, 28, 18, 15, 20, 589959)),
        ),
    ]
