# Generated by Django 3.2.9 on 2022-01-29 02:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0044_alter_tracker_sysdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='Sysdate',
            field=models.DateField(default=datetime.datetime(2022, 1, 28, 18, 18, 27, 267463)),
        ),
    ]
