# Generated by Django 3.2.9 on 2022-01-29 02:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0045_alter_tracker_sysdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addempdata',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addprojectdata',
            name='prstartdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='Sysdate',
            field=models.DateField(default=datetime.datetime(2022, 1, 28, 18, 20, 40, 130983)),
        ),
    ]
