# Generated by Django 3.2.9 on 2022-01-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0052_remove_tracker_trid'),
    ]

    operations = [
        migrations.CreateModel(
            name='loginapi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=35)),
                ('status', models.CharField(max_length=35)),
                ('datetime', models.CharField(max_length=35)),
                ('starttime', models.CharField(max_length=35)),
                ('enddate', models.CharField(max_length=35)),
            ],
        ),
    ]
