# Generated by Django 3.2.9 on 2022-01-31 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0054_auto_20220130_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginapi',
            old_name='enddate',
            new_name='endtime',
        ),
    ]
