# Generated by Django 3.2.9 on 2022-01-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0055_rename_enddate_loginapi_endtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='addempdata',
            name='uploadimage',
            field=models.ImageField(default='', upload_to='media'),
        ),
    ]
