# Generated by Django 3.2.9 on 2022-02-01 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0056_addempdata_uploadimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addempdata',
            name='uploadimage',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
