# Generated by Django 3.2.9 on 2022-02-02 04:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0057_alter_addempdata_uploadimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginapi',
            name='toady_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 2, 4, 15, 9, 811915, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
