# Generated by Django 3.2.9 on 2022-02-12 19:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0058_loginapi_toady_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='keyboardclickevent',
            field=models.CharField(default=datetime.datetime(2022, 2, 12, 19, 26, 31, 713112, tzinfo=utc), max_length=35),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tracker',
            name='mousecelickevent',
            field=models.CharField(default=datetime.datetime(2022, 2, 12, 19, 26, 53, 195005, tzinfo=utc), max_length=35),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tracker',
            name='ScreenShot',
            field=models.ImageField(default='', upload_to='Screenshot/'),
        ),
    ]
