# Generated by Django 3.2.9 on 2022-02-12 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0059_auto_20220212_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='keyboardclickevent',
            new_name='keyboardClickevent',
        ),
        migrations.RenameField(
            model_name='tracker',
            old_name='mousecelickevent',
            new_name='mouseClickevent',
        ),
    ]
