# Generated by Django 3.2.9 on 2022-02-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0060_auto_20220212_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=35)),
                ('userfname', models.CharField(max_length=30)),
                ('userlname', models.CharField(max_length=30)),
                ('useremail', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
