# Generated by Django 3.2.9 on 2022-02-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0061_superusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addempdata',
            name='uploadimage',
            field=models.ImageField(default='', upload_to='profile_image/'),
        ),
    ]
