# Generated by Django 3.2.9 on 2022-02-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0063_alter_tracker_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='ScreenShot',
            field=models.ImageField(default='', upload_to='Screenshot/'),
        ),
    ]
