# Generated by Django 3.2.9 on 2022-02-19 01:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0064_alter_tracker_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addempdata',
            name='dob',
            field=models.DateField(default=datetime.datetime(2022, 2, 19, 1, 12, 33, 189293, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
