# Generated by Django 3.2.9 on 2022-02-19 01:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0065_alter_addempdata_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='addempdata',
            name='joindate',
            field=models.DateField(default=datetime.datetime(2022, 2, 19, 1, 31, 6, 215180, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
