# Generated by Django 4.1.3 on 2022-11-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0068_addempdata_addprojectdata_addtaskdata_loginapi_superusers_tracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addempdata',
            name='Address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='addempdata',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='addprojectdata',
            name='prdatails',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='addtaskdata',
            name='Task_Details',
            field=models.CharField(max_length=250),
        ),
    ]
